### ISSUE TITLE
Excel return output but it throwing 'org.decampo.xirr.NonconvergenceException: Newton-Raphson failed to converge within 10000 iterations' 

### ISSUE THREAD

**Issue by devpatidar17** [RayDeCampo/java-xirr#14]
I tried with excel, the same transaction returned rate = -0.724636607244611.
But code is throwing 'org.decampo.xirr.NonconvergenceException: Newton-Raphson failed to converge within 10000 iterations' .

Below is my transactions with code.
@Test
public void xirrTestXirrTestTest(){
    double rate = new Xirr(
            new Transaction(-1498500, "2018-08-30"),
            new Transaction(-1500, "2018-08-30"),
            new Transaction(-499500, "2019-01-10"),
            new Transaction(-500, "2019-01-10"),
            new Transaction(-499500, "2019-03-07"),
            new Transaction(-500, "2019-03-07"),
            new Transaction(-44955000, "2019-03-19"),
            new Transaction(-45000, "2019-03-19"),
            new Transaction(44630158.4897253, "2019-03-31"),
            new Transaction(44674.8333230484, "2019-03-31")

    ).xirr();
    System.out.println(rate); 
}

**Comment by RayDeCampo** [comment]
This will converge if you supply a better guess:

```
    @Test
    public void xirr_issue14() {
        double rate = Xirr.builder()
            .withGuess(-.5)
            .withTransactions(
                new Transaction(-1498500, "2018-08-30"),
                new Transaction(-1500, "2018-08-30"),
                new Transaction(-499500, "2019-01-10"),
                new Transaction(-500, "2019-01-10"),
                new Transaction(-499500, "2019-03-07"),
                new Transaction(-500, "2019-03-07"),
                new Transaction(-44955000, "2019-03-19"),
                new Transaction(-45000, "2019-03-19"),
                new Transaction(44630158.4897253, "2019-03-31"),
                new Transaction(44674.8333230484, "2019-03-31")
            ).xirr();
        assertEquals(-0.7246366, rate, TOLERANCE);
    }
```

**Comment by sanket-lathiya-jupiter** [comment]
How to determine the better guess?
