### ISSUE TITLE
What is formula of calculating guess value which pass with transactions in Xirr.

### ISSUE THREAD

**Issue by devpatidar17** [RayDeCampo/java-xirr#15]
Below is an answer is given by you of my last question.
You pass guess value (-.5), I want to know how you calculate guess value.? 

@Test
    public void xirr_issue14() {
        double rate = Xirr.builder()
            .withGuess(-.5)
            .withTransactions(
                new Transaction(-1498500, "2018-08-30"),
                new Transaction(-1500, "2018-08-30"),
                new Transaction(-499500, "2019-01-10"),
                new Transaction(-500, "2019-01-10"),
                new Transaction(-499500, "2019-03-07"),
                new Transaction(-500, "2019-03-07"),
                new Transaction(-44955000, "2019-03-19"),
                new Transaction(-45000, "2019-03-19"),
                new Transaction(44630158.4897253, "2019-03-31"),
                new Transaction(44674.8333230484, "2019-03-31")
            ).xirr();
        assertEquals(-0.7246366, rate, TOLERANCE);
    }

**Comment by RayDeCampo** [comment]
It's more of an art than a science.  If you are trying to always get an answer, you could try a loop where you try different initial guesses.  Keep in mind the lowest possible value is -1 but there is no upper limit.
