### ISSUE TITLE
Recalculation of xirr

### ISSUE THREAD

**Issue by promwtc** [RayDeCampo/java-xirr#23]
Hi, i have a use case where i know a calculated xirr value (using your library) and i know a changed / new current value. Is it possible to recalculate the xirr without knowing the rest of the transactions?

**Comment by RayDeCampo** [comment]
This is really a math question :-)

But I do not think it is possible, math-wise.

**Comment by promwtc** [comment]
> This is really a math question :-)
> 
> But I do not think it is possible, math-wise.

I understand :) how about if we know 3 of the data points? Xirr, old current value and new current value? Based on the formula that you have written do you think it is possible to calculate the new xirr?

**Comment by RayDeCampo** [comment]
Suppose there is an investment earning 12%.  Alice puts in $2000.  Bob puts in $1000 and then the next year ups his investment by $1120.  After two years they each have xirr 12% and have the same amount of money:


       double xirr = new Xirr(
                new Transaction(-2000, "2010-01-01"),
                new Transaction( 2508.80, "2012-01-01")
            ).xirr();
        assertEquals(0.12, xirr, TOLERANCE);

        xirr = new Xirr(
                new Transaction(-1000, "2010-01-01"),
                new Transaction(-1120, "2011-01-01"),
                new Transaction( 2508.8, "2012-01-01")
            ).xirr();
        assertEquals(0.12, xirr, TOLERANCE);


Alice and Bob have the same current value and xirr, but their future xirr may diverge. E.g., assume the investment earns nothing in year three.  Now Alice's xirr is 7.8 while Bob's is 7.0:


        xirr = new Xirr(
                new Transaction(-2000, "2010-01-01"),
                new Transaction( 2508.80, "2013-01-01")
            ).xirr();
        assertEquals(0.0784054, xirr, TOLERANCE);

        xirr = new Xirr(
                new Transaction(-1000, "2010-01-01"),
                new Transaction(-1120, "2011-01-01"),
                new Transaction( 2508.8, "2013-01-01")
            ).xirr();
        assertEquals(0.07017195, xirr, TOLERANCE);
