### ISSUE TITLE
When the yield is below -0.64, it will throw "IllegalArgumentException: Newton-Raphson failed to converge within 10000 iterations."

### ISSUE THREAD

**Issue by tanzhi963** [RayDeCampo/java-xirr#5]
When the yield is below -0.64, it will throw "IllegalArgumentException: Newton-Raphson failed to converge within 10000 iterations."

I also tried many other numbers with a yield higher than -0.64, and the code didn't throw an exception.
But once the yield is lower than -0.64, it will throw an exception.

Below is my test code

    @Test
    public void xirrTestXirrTestTest(){
        double rate = new Xirr(
                new Transaction(-2610, "2001-06-22"),
                new Transaction(-2589, "2001-07-03"),
                new Transaction(-5110, "2001-07-05"),
                new Transaction(-2550, "2001-07-06"),
                new Transaction(-5086, "2001-07-09"),
                new Transaction(-2561, "2001-07-10"),
                new Transaction(-5040, "2001-07-12"),
                new Transaction(-2552, "2001-07-13"),
                new Transaction(-2530, "2001-07-16"),
                new Transaction(29520, "2001-07-17")

        ).xirr();
        System.out.println(rate); 
    }

**Comment by RayDeCampo** [comment]
When I incorporate your test into the existing XirrTest class, I get the output:

{{{
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.decampo.xirr.XirrTest
-0.7640294070510181
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.147 sec
}}}

As you can see the rate is -76.4% and there are no errors.

Perhaps you are using an older version?  Make sure you are using version 0.1 from maven central (https://search.maven.org/artifact/org.decampo/xirr/0.1/jar).

**Comment by RayDeCampo** [comment]
@tanzhi963 I realized I had not updated github with the information for the release of 0.1 in August.  Please give it a try with that version and let me know how that works.

**Comment by tanzhi963** [comment]
After changing the version, the test code passed, very good!
Thank you very much for your code. The style of your code is great and it helps me a lot.

**Comment by tanzhi963** [comment]
Sorry, the following data will still report an exception "Newton-Raphson failed to converge within 10000 iterations."    

Version V0.1 will report an exception when the rate of return is less than -0.8351.


@Test
    public void xirrTestXirrTestTest(){
        double rate = new Xirr(
                new Transaction(-2610, "2001-06-22"),
                new Transaction(-2589, "2001-07-03"),
                new Transaction(-5110, "2001-07-05"),
                new Transaction(-2550, "2001-07-06"),
                new Transaction(-5086, "2001-07-09"),
                new Transaction(-2561, "2001-07-10"),
                new Transaction(-5040, "2001-07-12"),
                new Transaction(-2552, "2001-07-13"),
                new Transaction(-2530, "2001-07-16"),
                new Transaction(-9840, "2001-07-17"),
                new Transaction(38900, "2001-07-18")

        ).xirr();
        System.out.println(rate); 
    }

**Comment by chzhong** [comment]
> Sorry, the following data will still report an exception "Newton-Raphson failed to converge within 10000 iterations."
> 
> Version V0.1 will report an exception when the rate of return is less than -0.8351.
> 
> @test
> public void xirrTestXirrTestTest(){
> double rate = new Xirr(
> new Transaction(-2610, "2001-06-22"),
> new Transaction(-2589, "2001-07-03"),
> new Transaction(-5110, "2001-07-05"),
> new Transaction(-2550, "2001-07-06"),
> new Transaction(-5086, "2001-07-09"),
> new Transaction(-2561, "2001-07-10"),
> new Transaction(-5040, "2001-07-12"),
> new Transaction(-2552, "2001-07-13"),
> new Transaction(-2530, "2001-07-16"),
> new Transaction(-9840, "2001-07-17"),
> new Transaction(38900, "2001-07-18")
> 
> ```
>     ).xirr();
>     System.out.println(rate); 
> }
> ```

I tried your data with Excel and still failed to find the result.

Passing -0.8 as the guess will figure out -0.8353404468272652.

**Comment by RayDeCampo** [comment]
Please try again using the latest code.  I have addressed both the cases sited in this issue and added them as unit tests.  You will have to build from the latest yourself, I have not yet made a release for maven.

Thanks for the report.  If you find any further examples, please open a new bug report (do not re-open this one).  But I am hopeful that the new changes will prove more resilient.
