### ISSUE TITLE
Expose Newton-Raphson options to Xirr client

### ISSUE THREAD

**Issue by RayDeCampo** [RayDeCampo/java-xirr#6]
Expose the Newton-Raphson options for tolerance, iterations and initial guess to the client of the Xirr class.

**Comment by hrj** [comment]
This issue is very critical. The following real world case is failing to converge in 10000 iterations:

```
 -11.900 on 2018-05-15
 -10.175 on 2018-05-16
  20.275 on 2018-08-09
  20.100 on 2018-08-10
  -4.350 on 2019-03-19
  -4.725 on 2019-03-20
  -3.200 on 2019-04-08
  -3.050 on 2019-04-09
  -2.900 on 2019-04-10
  -2.800 on 2019-04-11
  -2.700 on 2019-04-12
  -2.600 on 2019-04-15
  -2.500 on 2019-04-16
  22.500 on 2019-04-16
```

**Comment by hrj** [comment]
Looks like the number of iterations was not the problem. I tried the latest master commit and that doesn't throw an exception for that dataset. However, it does for another set. I will raise a separate issue for that.
